language: node_js
node_js:
- node
before_script:
- npm run lint
notifications:
  email: false
  slack:
    secure: uIfNA2rMGimlIYsTFyZKkP6/CBJsNOjMMtOFjpAKBwrU1f0W/EV10uYkocxtaflwhYiT8fk/SCNo0mud0mKcr7LCyoVm9HgeDsbQdL2M9VdjH8Li8Ck0rIiMbPiegqsLYscZpSkj4W26fC8FX9rvHoWBbe7/UCLEYvYENY2rE2POjCIXPXP0v3ZwshFSw5Watc4FsIj4OvrcCTAbQIGr85b18X0DIDm0aT8DhpAlfJrbhDmVVVN533msttOxoaX+7jguIw4vGkBaeCullIqNqpFeP4ZLj5W3WFiVTaPnY5+gsXxIv0wQbui0TBQcstD3JeDucY2V68Nzjh2uXqCWcBNxsFqN7TbtG7bRgrno9h5UiZSQ4liU8MvnNpcD9rOivaPkQ5PRpKBVLwlqPzMF1QyuIQ69uQlQ3hEnPu2Kr+QHmVwrjo17WzWXeLXOiGXeu0SQbyh7SZHVJrfNHkb5VswiFr+SnKKVQej3X9FBpY619PeUuvlyQBDic0v9NMc5AOSttinRFDNbvwQ/9AmTy2cGRkZDxbwiwdgtBR98T9FqnaP0Gh5Tylbkgkj9kXKGM4UM5edEGuhmxvF7CqSrs2/2Jbqvl/9MoQ4CxchOE3eFW+si3qzgCRP/WXkE4y6XIVw+tqLNuJh6odP3+X3MJ/+9qURFZG/ZM97pniraAcE=
