name: GitHub CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint and Test
        run: |
          npm install
          npm run lint
          npm test
